'use client';

// Mode B's "confirm your room" step — sits between vision analysis
// (which extracts dimensions + room_type) and the palette/picker
// (where the user commits to the design). Renders a top-down
// architectural floorplan SVG generated by lib/floorplan.ts and
// asks the user to confirm or re-upload.
//
// Owner directive 2026-05-26:
//   - Floorplan editability deferred to v2 — v1 just shows the
//     architectural plan with measurements; user confirms or rejects.
//   - Layout depth = "Dimensions + product silhouettes in suggested
//     positions" — generic furniture boxes per core categories of
//     the room type, not Claude-driven, not editable.
//
// Renders nothing while Mode A is active — gated on flowMode='b' at
// the call site (upload-form.tsx).

import { generateFloorplanSvg } from '@/lib/floorplan';
import { cn } from '@/lib/utils';

interface FloorplanConfirmationProps {
  /** Vision-extracted dimensions from rooms.analysis.dimensions_approximate_m.
   *  Any axis can be null when Claude couldn't infer it confidently. */
  width_m: number | null;
  depth_m: number | null;
  /** Vision-extracted room_type (e.g. "living_room"). null falls back
   *  to the default layout in the SVG generator. */
  roomType: string | null;
  /** User accepts the floorplan — proceed to palette + picker. */
  onConfirm: () => void;
  /** User rejects the dimensions — go back and re-upload. */
  onReupload: () => void;
}

export function FloorplanConfirmation({
  width_m,
  depth_m,
  roomType,
  onConfirm,
  onReupload,
}: FloorplanConfirmationProps) {
  // No-dimensions path. Vision can return null for either axis when
  // Claude couldn't infer them confidently (skylit ceiling, extreme
  // wide-angle shot, partial view). We let the user proceed anyway —
  // the downstream picker still works without dimensions; only the
  // dimension-aware filter (#45) becomes a no-op for that render.
  if (!width_m || !depth_m) {
    return (
      <section className="mt-8 rounded-2xl border border-ink/[0.06] bg-paper-warm p-6 md:p-8">
        <h2 className="font-display text-h3 text-ink">Couldn&apos;t read your room dimensions</h2>
        <p className="mt-3 max-w-md text-[14px] text-ink-soft">
          Vision returned the room type ({roomType?.replace(/_/g, ' ') ?? 'unknown'}) but
          couldn&apos;t infer width and depth confidently from this photo. You can still
          proceed — the picker will skip dimension filtering for this render — or upload
          a different photo with more of the floor visible.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <button
            type="button"
            onClick={onReupload}
            className="rounded-full border border-ink/15 px-5 py-2.5 font-mono text-meta uppercase tracking-eyebrow text-ink hover:bg-ink/[0.04]"
          >
            Upload another photo
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className="rounded-full bg-ink px-5 py-2.5 font-mono text-meta uppercase tracking-eyebrow text-cream hover:bg-ink/90"
          >
            Skip — continue
          </button>
        </div>
      </section>
    );
  }

  const svgString = generateFloorplanSvg({ width_m, depth_m, roomType });
  const roomLabel = roomType?.replace(/_/g, ' ') ?? 'room';

  return (
    <section className="mt-8 rounded-2xl border border-ink/[0.06] bg-paper-warm p-6 md:p-8">
      <header>
        <p className="font-mono text-meta uppercase tracking-eyebrow text-ink-faint">
          Step 2 · confirm your space
        </p>
        <h2 className="mt-2 font-display text-h3 text-ink">
          Here&apos;s how we&apos;ve read your {roomLabel}.
        </h2>
        <p className="mt-3 max-w-xl text-[14px] text-ink-soft">
          {width_m.toFixed(1)} m × {depth_m.toFixed(1)} m. The furniture boxes are
          suggestions for where {roomLabel} pieces typically sit — you&apos;ll pick the
          actual products in the next step.
        </p>
      </header>

      <div className={cn('mt-6 flex justify-center rounded-xl bg-cream p-4 md:p-6')}>
        {/* SVG is generated server-deterministic; no XSS risk because
            the only user input is room_type (an enum from vision.ts)
            and the dimensions (numbers we serialise via toFixed). */}
        <div
          className="max-w-full"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: svgString }}
        />
      </div>

      <div className="mt-6 flex flex-wrap gap-3">
        <button
          type="button"
          onClick={onReupload}
          className="rounded-full border border-ink/15 px-5 py-2.5 font-mono text-meta uppercase tracking-eyebrow text-ink hover:bg-ink/[0.04]"
        >
          Dimensions wrong — re-upload
        </button>
        <button
          type="button"
          onClick={onConfirm}
          className="rounded-full bg-ink px-5 py-2.5 font-mono text-meta uppercase tracking-eyebrow text-cream hover:bg-ink/90"
        >
          Looks right — continue
        </button>
      </div>
    </section>
  );
}
